spring:
  application:
    name: springbootevent

  mail:
    host: smtp.163.com
    port: 465
    username: ss123456ss1020@163.com
    #password: JVsaadJ49X25c7V8
    password: xxx
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          enable: true
          ssl:
            # 设为true时 端口号设为 465 设为false时 端口号设为25
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true

logging:
  level:
    root: WARN
    org:
      springframework:
        web: DEBUG

    com:
      spring:
        bootevent:
          messageevent: debug

message:
  event:
    message:
      pool:
        # 核心线程数，默认为8
        core-size: 8
        # 最大线程数
        max-size: 10240
        # 队列容量
        queue-capacity: 102400
        # 线程活 keep-alive 时间，默认是60（单位毫秒）
        keep-alive: 100000
        # 开启线程池
        enabled: true
      thread-name-prefix: messageThreadPoolExecutor
      # sms
      # email
      # 日志配置
      logs:
        log: true #开启消息事件日志推送
        default-log: true #开启默认找不到监听通道日志推送
