spring:
  application:
    name: springbootevent

  mail:
    host: smtp.163.com
    port: 465
    username: ss123456ss1020@163.com
    #password: JVsaadJ49X25c7V8
    password: xxx
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          enable: true
          ssl:
            # 设为true时 端口号设为 465 设为false时 端口号设为25, 如果ssl不成功，改成false，使用25端口
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true

logging:
  level:
    root: WARN
    org:
      springframework:
        web: DEBUG

    com:
      spring:
        bootevent:
          messageevent: debug
